vendor: add A/B installation support

diff --git a/updater/update-binary-a b/updater/update-binary-a
--- a/updater/update-binary-a
+++ b/updater/update-binary-a
@@ -1,56 +1,83 @@
 #!/sbin/sh
-# LazyFlasher installer backend (for helper functions only)
+# TWRP A/B Installer Backend
+# by osm0sis, Dees_Troy and topjohnwu
+# Adapted by Giovix92 for SHRP
 
-tmp=/data/local/twrp-install
+OUTFD=/proc/self/fd/$2;
+ZIPFILE="$3";
 
-if [ "$3" ]; then
-	zip=$3
-	console=/proc/$$/fd/$2
-	# write the location of the console buffer to /tmp/console for other scripts to use
-	echo "$console" > /tmp/console
-else
-	console=$(cat /tmp/console)
-	[ "$console" ] || console=/proc/$$/fd/1
-fi
+ui_print() { $BOOTMODE && echo "$1" || echo -e "ui_print $1\nui_print" >> $OUTFD; }
+abort() { ui_print "$1"; exit 1; }
 
-print() {
-	if [ "$1" ]; then
-		echo "ui_print $1" > "$console"
-	else
-		echo "ui_print  " > "$console"
-	fi
-	echo
-}
+# detect Magisk Manager/booted flashing
+ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false;
+$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true;
 
-abort() {
-	[ "$1" ] && {
-		print "Error: $1"
-		print "Aborting..."
-	}
-	cleanup
-	print "Failed to patch boot image!"
-	exit 1
-}
+ui_print "----------------------------------------";
+ui_print "-                                       ";
+ui_print "- SHRP installer for A/B devices        ";
+ui_print "- Device: $device                       ";
+ui_print "- Version: 2.2 official                 ";
+ui_print "-                                       ";
+ui_print "----------------------------------------";
+ui_print " ";
 
-cleanup() {
-	[ "$zip" ] && rm /tmp/console
-}
+# /dev/tmp is safe for both booted and recovery installs
+tmp=/dev/tmp/shrp-install;
+# target partition without the slot suffix
+target=/dev/block/bootdevice/by-name/boot;
 
-extract() {
-	rm -rf "$2"
-	mkdir -p "$2"
-	unzip -o "$1" -d "$2" || abort "Failed to extract zip to $2!"
-}
+ui_print "[i] Unpacking the installer...";
+ui_print " ";
+rm -rf $tmp;
+mkdir -p $tmp;
+unzip -o "$ZIPFILE" -d $tmp || abort "[!!] Failed to extract zip! Check recovery logs.";
 
-# Unpack the installer
-[ "$zip" ] && {
-	extract "$zip" "$tmp"
-}
-cd "$tmp"
-toolname="/magiskboot"
-tool="$tmp$toolname"
-targetfile="/boot.img"
-target="$tmp$targetfile"
+ui_print "[i] Copying SHRP add-ons...";
+cp -r $tmp/Files/SHRP/addons /sdcard7
 
-chmod 755 "$tool"
+cd $tmp;
+cp $tmp/Files/SHRP/addons/magiskboot $tmp;
+tool=$tmp/magiskboot;
+test "$tool" || abort "[!!] No magiskboot binary found! Aborting.";
+recoverycpio=`(ls ramdisk-twrp.cpio || ls ramdisk-recovery.cpio) 2>/dev/null`;
+test "$recoverycpio" || abort "[!!] No SHRP ramdisk cpio found! Aborting.";
+
+chmod 755 $tool;
+
+workDIR=$tmp/work/;
+mkdir -p $workDIR;
+cd $workDIR;
+
+for slot in a b; do
+  ui_print "[i] Making a backup of boot_$slot...";
+  dd if=/dev/block/bootdevice/by-name/boot_$slot of=/sdcard/boot_$slot.img;
+  ui_print "[i] Running boot image patcher on slot $slot...";
+  dd if=/dev/block/bootdevice/by-name/boot_$slot of=recovery.img;
+
+  $tool unpack -h recovery.img;
+
+  # kernel string want_initramfs -> skip_initramfs (Magisk)
+  $tool hexpatch kernel 77616E745F696E697472616D6673 736B69705F696E697472616D6673;
+  # kernel string trip_initramfs -> skip_initramfs (SuperSU)
+  $tool hexpatch kernel 747269705F696E697472616D6673 736B69705F696E697472616D6673;
+
+  # boot.img header cmdline remove skip_override (flar2 patch)
+  sed -i "s|$(grep '^cmdline=' header | cut -d= -f2-)|$(grep '^cmdline=' header | cut -d= -f2- | sed -e 's/skip_override//' -e 's/  */ /g' -e 's/[ \t]*$//')|" header;
+
+  cp -f $tmp/$recoverycpio $workDIR;
+  cp -f $recoverycpio ramdisk.cpio;
+  $tool repack recovery.img newRec.img;
+
+  dd if=newRec.img of=/dev/block/bootdevice/by-name/boot_$slot || abort "[!!] Unable to find patched bootimg! Aborting.";
+  rm -r *;
+
+  ui_print "[i] Slot $slot patched!";
+done;
+ui_print "[i] Cleaning up...";
+cd /;
+rm -rf /dev/tmp;
+ui_print "[i] Boot image patching complete!";
+ui_print "[i] Note: you're now unrooted.!";
+
 
